name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install test dependencies
      run: |
        python -m pip install -U pip
        pip install pytest pytest-cov
    - name: Test Algorithms
      run: |
        pytest --cov-report=xml
  - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: coverage.xml
        directory: .
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
